### ISSUE TITLE
使用Composer安装Laravel项目出现文件缺失

### ISSUE THREAD

**Issue by stonezhng** [johnlui/Learn-Laravel-5#11]
在目标目录下运行
`composer create-project laravel/laravel testProject`

生成的项目会有出现某些文件缺失的情况，比如

/app/http/ 目录下缺少routes.php文件，缺少Requests文件夹。

**Comment by JohnnyLiu2** [comment]
routes.php 文件现在都放到 routes文件夹下了, 主要就是 web.php和 api.php
