### ISSUE TITLE
【大作业】评论管理遇到的问题

### ISSUE THREAD

**Issue by toyuanx** [johnlui/Learn-Laravel-5#13]
在删除article之后，应该删除对应的评论，这里涉及到comments与article两张表，我在Admin\ArticleController下添加了如下代码：
```php
Comment::where('article_id', '=', $id)->delete();
```
涉及两张相关联的表，有更好的删除方法吗？

**Comment by zachMelody** [comment]
Article的model中
`public function deleteC()
    {
        return($this->hasMany(Comment::class)->delete());
    }`
然后在ArticleController中的`public function destroy(Article $article)
    {}`添加`$article->delete()`和`$article->deleteC()`

初学，不知道是否有更简单的呢？

**Comment by zachMelody** [comment]
遇到个小问题解决了
`if ($article->deleteC() || $article->delete())`
删除评论在前，否则先删文章会找不到对应的评论
