### ISSUE TITLE
请问在Laravel中使用分层结构的时候，如果业务逻辑比较复杂的话放在那一层?

### ISSUE THREAD

**Issue by KDF5000** [johnlui/Learn-Laravel-5#2]
**johnlui**，你好，看了你的入门教程，收获很大，教程里写的思路也很好，很适合开发者学习，但是有一个小小的疑问，如果有比较负责的业务逻辑的话，比如需要多个`Model`的数据进行拼装然后返回给客户端（`API`的形式），就像`java`中可能会建立一个`Service`层处理这些逻辑，在`Laravel`中有什么好的建议？

**Comment by johnlui** [comment]
Laravel 的 Model 由于继承了 Eloquent 导致做所有事都非常简单，不需要复用的复杂逻辑直接写在控制器的响应 function 中便是，如果需要代码复用，可以封装到某一个 Model 中，或者自己新建 Service 类，Laravel 5 使用 PSR-4 自动加载机制，连命名空间都不要注册了，直接按照实际路径写好直接调用便是。

**Comment by KDF5000** [comment]
@johnlui 好的，谢谢！
