### ISSUE TITLE
有考虑加入Swoole的教程？

### ISSUE THREAD

**Issue by super-jackson** [johnlui/Learn-Laravel-5#21]
FPM下，Laravel性能一直被诟病，虽有精简的Lumen，但依然会有每次加载文件、初始化资源的开销。
基于Swoole Http Server常驻内存后(替代FPM)，可节省这部分开销，同时还可以利用Swoole的很多特效，例如协程、异步IO。

**Comment by johnlui** [comment]
这是入门教程，这个技术还是太“牛逼”了。

Swoole 是我很喜欢的项目，但是 Swoole 教信众过于狂热，我不喜欢。

我在微博上说过，Swoole 的本质是采用 PHP 作为其 DSL 的基于 epoll 的 C 写的异步网络库，属于典型的扮猪吃老虎。PHP 是单线程阻塞语言，跟 Swoole 的运行模型和编程思想都天差地别。

当然用 Swoole 加速 xx 项目的事儿我目前还没做过，不便评价。
