### ISSUE TITLE
报错了

### ISSUE THREAD

**Issue by codesourse** [johnlui/Learn-Laravel-5#3]
Warning: require(/Applications/MAMP/htdocs/Learn-Laravel-5-master/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /Applications/MAMP/htdocs/Learn-Laravel-5-master/bootstrap/autoload.php on line 17

Fatal error: require(): Failed opening required '/Applications/MAMP/htdocs/Learn-Laravel-5-master/bootstrap/../vendor/autoload.php' (include_path='.:/Applications/MAMP/bin/php/php7.0.0/lib/php') in /Applications/MAMP/htdocs/Learn-Laravel-5-master/bootstrap/autoload.php on line 17

**Comment by johnlui** [comment]
这是因为下载了源码之后需要 composer update 才能运行的缘故，已在最新版中给出说明。
