### ISSUE TITLE
2016 版 Laravel 系列入门教程（二）【最适合中国人的 Laravel 教程】

### ISSUE THREAD

**Issue by johnlui** [johnlui/Learn-Laravel-5#5]
> #### 本教程示例代码见：https://github.com/johnlui/Learn-Laravel-5
> 
> 在任何地方卡住，最快的办法就是去看示例代码。

本篇文章中，我将跟宝宝们一起学习 Laravel 框架最重要的部分——路由系统。

如果你读过旧的基于 Laravel 5.0 版本的此教程，你会发现那篇文章里大书特书的 Auth 系统构建已经被 Laravel 捎带手给解决了。在更早的 Laravel 4 版本的教程中，实际上我是通过让大家自己动手构建高难度的 Auth 系统来提高短期学习曲线的斜率，以便宝宝们能更快地感受到 Laravel 运行的原理。但是很遗憾，现在的 Auth 系统实在是太强大了，执行几句命令就激活了这个功能，新手其实还是云里雾里。为了弥补这个缺憾，本宝宝决定赤膊上阵，手刃路由系统，直接给大家展示 Laravel 是如何组织 MVC 架构，来控制网站运行的。
## 初识路由

路由系统是所有 PHP 框架的核心，路由承载的是 URL 到代码片段的映射，不同的框架所附带的路由系统是这个框架本质最真实的写照，一丝不挂，一览无余。Laravel 路由中文文档：http://laravel-china.org/docs/5.1/routing

Laravel 5 之后就把路由放到了 `learnlaravel5/app/Http/routes.php` 这个位置，我们先看一下目前路由中仅存的几行代码：

``` php
Route::get('/', function () {
    return view('welcome');
});

Route::auth();

Route::get('/home', 'HomeController@index');
```

中间的一行代码 `Route::auth();` 就是 Auth 系统自动注入的路由配置，我们不用深究，我们的注意力主要集中头三行和最后一行代码上。
## 命名空间

本宝宝一直认为 Laravel 5 除了性能大幅提升之外相对于 4 最大的进步就在于新的命名空间规划：更清晰，更合理，更有利于新手。
### Laravel 4 失败的简洁

Laravel 4 时代，大量的代码都运行在根命名空间下，路由、Controller、Model 等等。看起来这么做可以少写几行枯燥的 `use xxxx;`，实则是对于命名空间的误使用，而且对于新手学习命名空间是有毒的。
### 绝对类名

Laravel 5 全面引入了 psr-4 命名空间标准：命名空间和实际文件所在的文件夹层级一致，文件夹首字母大写即为此文件的约定命名空间。举个小栗子：`learnlaravel5/app/Http/Controllers/HomeController.php` 的绝对类名为：`\App\Http\Controllers\HomeController`，`learnlaravel5/app/User.php` 的绝对类名为：`\App\User`。

“绝对类名”是本宝宝自创的：在启用了命名空间的系统中，子命名空间下的类有一个全局都可以直接访问的名称，这个名称就是该类的命名空间全称。虽然命名空间在“实用主义”的 PHP 语言里看起来十分古怪，不过他也还是 PHP 嘛，依然遵循 PHP 的运行原理和哲学。同理，Laravel 无论多么强大，他都是 PHP 代码写成的，所以当你苦于 Laravel 没有提供某个你需要的功能时，不要惊慌不要着急，just write the code in the PHP way。

> psr-4 的官方英文文档在这里：http://www.php-fig.org/psr/psr-4/
### 好用的资料

命名空间其实没什么特别难的地方，我曾经写过一篇文章专门扒光命名空间的秘密：[《PHP 命名空间 解惑
》](https://lvwenhan.com/php/401.html)
### 闭包路由

路由文件中前三行即为闭包路由：

``` php
Route::get('/', function () {
    return view('welcome');
});
```

闭包路由使用闭包作为此条请求的响应代码，方便灵活，很多简单操作直接在闭包里解决即可。例如“输出服务器当前时间”：

``` php
Route::get('now', function () {
    return date("Y-m-d H:i:s");
});
```

如果你想得到北京时间，请在 `learnlaravel5/config/app.php` 第 55 行左右把 timezone 设置为上海：

``` php
'timezone' => 'Asia/Shanghai',
```

这时候访问 http://fuck.io:1024/now 可以得到如下结果：

![](https://dn-lvwenhan-com.qbox.me/2016-05-20-14635078555186.jpg)
### 控制器@方法 路由

闭包路由虽然灵活强大，不过大多数场景下我们还是需要回归到 MVC 架构的：

``` php
Route::get('/home', 'HomeController@index');
```

这行路由代码的意思想必大家都能猜到一二了：当以 GET 方法访问 `http://fuck.io:1024/home` 的时候，调用 HomeController 控制器中的 index 方法（函数）。同理，你可以使用 `Route::post('/home', 'HomeController@indexPost');` 响应 POST 方法的请求。
### 控制器@方法 调用原理浅析

Laravel 的路由跟所有 PHP 框架的路由一样，都是用的最简单直接的 PHP 方式来调用控制器中的方法的：使用字符串初始化类得到对象，调用对象的指定方法，返回结果。下面我简单罗列几步对 Laravel 路由调用过程的探测，感兴趣的话可以自己研究。
#### `learnlaravel5/app/Providers/RouteServiceProvider.php`

全局搜索 `routes.php`，我们找到了这个文件。此文件最后的 mapWebRoutes 方法，给所有的路由统一加进了一个路由组，定义了一个命名空间和一个中间件：

``` php
protected function mapWebRoutes(Router $router)
{
    $router->group([
        'namespace' => $this->namespace, 'middleware' => 'web',
    ], function ($router) {
        require app_path('Http/routes.php');
    });
}
```

顺着这个函数往上看，你会发现命名空间定义的地方：

``` php
protected $namespace = 'App\Http\Controllers';
```

之后命名空间、类、方法是如何传递的呢？
#### `learnlaravel5/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php`

经过简单的追踪，我们找到了这个文件。让我们在 dispatch 方法中增加一行 `var_dump($controller);`，刷新就可以看到页面上如下的输出：

![](https://dn-lvwenhan-com.qbox.me/2016-05-20-14636819645628.jpg)

这就是我们要调用的控制器类的“绝对类名”。
#### 最后一步

Laravel 使用了完整的面向对象程序架构，对控制器的调用进行了超多层封装，所以最简单地探测方式其实是手动抛出错误，这样就可以看到完整的调用栈：

在 HomeController 的 index 方法里的 return 之前增加一行 `throw new \Exception("我故意的", 1);`，刷新页面，你将看到以下画面：

![](https://dn-lvwenhan-com.qbox.me/2016-05-20-14636830965542.jpg)

我们可以看到，是 `learnlaravel5/vendor/laravel/framework/src/Illuminate/Routing/Controller.php` 第 80 行最终驱动起了 HomeController：

``` php
public function callAction($method, $parameters)
{
    return call_user_func_array([$this, $method], $parameters);
}
```

具体的细节不再详解，宝宝如果感兴趣的话，把这些方法一个一个地都看一遍吧，相信对于你理解 Laravel 运行原理很有帮助。其实 PHP 跟字符串结合的紧密程度已经紧逼 js 和 JSON 了。结尾分享一个小彩蛋：[这个laravel路由怎么写?](https://www.zhihu.com/question/31330386/answer/51544599)

> ### 下一步：[2016 版 Laravel 系列入门教程（三）【最适合中国人的 Laravel 教程】](https://github.com/johnlui/Learn-Laravel-5/issues/6)

**Comment by huijian222** [comment]
您好 您在闭包路由中这样写
`Route::get('now', function () {
    return date("Y-m-d H:i:s");
});`
我在learnlaravel5/app/Http路径下 使用PHP -S 监听当前1024端口 

## 但当我访问时 提示 无当前路径

解决 
应该在public下 监听

**Comment by johnlui** [comment]
@huijian222 教程一中我确实是这么写的呦

> 为了尽可能地减缓学习曲线，推荐宝宝们使用 PHP 内置 web 服务器驱动我们的网站。运行以下命令：
> 
> ```
> cd learnlaravel5/public
> php -S 0.0.0.0:1024
> ```

**Comment by TuuuNya** [comment]
为何不推荐用 `php artisan serve`

**Comment by ZGilbert** [comment]
然而在 HomeController 的 index 方法里的 return 之前增加一行 throw new \Exception("我故意的", 1);
并没有抛出异常, 不知道什么情况..

**Comment by liqmhahaha** [comment]
why not use php artisan serve

**Comment by developbiao** [comment]
你好，我修改了timezone为Asia/Shanghai了，请求/now  返回"Sorry, the page you are looking for could not be found." 是什么原因呢？
update: 找到原因了，需要在routes/web.php文件中定义闭包路由。

**Comment by SuPeRZ66** [comment]
@developbiao  是不是要把php.ini中的timezone也改成这个
